
class InputMethod:
    NAME:str = None
    def __init__(self):
        ...
    def down(self,button):
        ...
    def up(self,button):
        ...
    def click(self,button):
        ...
    def moveRelative(self,x,y):
        ...